### ISSUE TITLE
Create short summary text intros for each pyramids on index.html

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#15]
From #12 

Add some description to each pyramid page, reachable by clicking on the correspondent button here:

![Screenshot 2019-04-19 at 11 41 44](https://user-images.githubusercontent.com/832220/56418733-206bd680-6298-11e9-9f4c-f9fede1d9b4d.png)

**Comment by micheleminno** [comment]
@aschrijver how can I correctly add an image in the [focus page](https://humanetech.community/focus/wellbeing/)?

**Comment by aschrijver** [comment]
I am not sure, because there are multiple ways. You should read the `minimal mistakes` instructions, and play with the concepts for a bit.

One way to add would be using regular (github-flavored) Markdown notation to have the image inline with the text, but there are also layouts that you can use (similar to the front page). For me Jekyll and Python is as new as it is for you.

https://mmistakes.github.io/minimal-mistakes/

**Comment by micheleminno** [comment]
> One way to add would be using regular Markdown notation to have the image inline with the text,

I did that:

`![pyramid-of-wellbeing|690x362](/assets/images/humanetech-pyramid-of-wellbeing-tinted-bare.png)`

but apparently it doesn't work. I thought I did some trivial error i.e. about the local image url.

Ok I'll figure it out.

**Comment by aschrijver** [comment]
Yea, I think it is something with the proper path you have to set. Also the image size will not work, I think.. this is Discourse markdown, not github-flavored (not sure for Jekyll, though).

Also if you need more images I uploaded all the images to: https://github.com/humanetech-community/styleguide/tree/master/community-artwork/humanetech-pyramids

If you use other images, then track where you got them, and what their license is. I want to add a Markdown doc to the site detailing its design choices.

**Comment by micheleminno** [comment]
> Also the image size will not work, I think..

Yes it was that, thank you:

https://humanetech.community/focus/wellbeing/

**Comment by aschrijver** [comment]
Very well done, Michele
