### ISSUE TITLE
Update README file with the procedures to contribute on the website code

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#16]
See comments on #14

**Comment by aschrijver** [comment]
For the time being I created a pinned forum topic that provides instructions for people who want to write their own blog entries on the Community Hub.

See this topic:

- https://community.humanetech.com/t/help-build-our-community-hub-and-publish-your-own-blog-entries-now/3824

For other website work more technical skilled contributors are required, and there is less need to provide step-by-step instructions. Hence this has less urgency and we need not do it for the MVP.
