### ISSUE TITLE
Create text descriptions for each pyramid category on their specific pages

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#20]
From #12 

Assign each category page a description.

**Comment by aschrijver** [comment]
I didn't intend to be this issue for giving each category a description. But the landing page itself (index.html) should have very short texts that describe each section.

This is the screenshot you made on https://github.com/humanetech-community/community-hub/issues/15 where the texts are still left-overs from the old site.

**Comment by micheleminno** [comment]
I intend this issue as adding a description to each category page, I'm doing it.
I'll change the issue title.

**Comment by micheleminno** [comment]
Check any contribution from [this thread](https://community.humanetech.com/t/contributions-sought-to-describe-each-category-in-our-new-future-htc-category-structure/3810).
