### ISSUE TITLE
Add a list of 'Our Stories' with links to forum member posts and an excerpt

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#25]
From #12

**Comment by aschrijver** [comment]
This needs some more information. Do you want a separate page 'Our stories' on the website?
Do we copy the text that people typed in the forum, or just a short excerpt + a link?

In case of a separate 'Our stories' document (and maybe also a separate header entry), I am wondering about the added value to the website, i.e. whether many people would especially open and read that website section.

We already have a Blog for member posts, which are also 'stories'. And if we show stories, we might better make them part of specific Docs sections, like e.g. "My smartphone humpback" in the `Wellbeing > Health` category, and "I quit Facebook and came to rest" in the `Wellbeing > Mindfulness` section.
