### ISSUE TITLE
Create an appropriate URL scheme for blog posts

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/community-hub#26]
Currently blog posts are given an URL based on the category they are assigned to, like this:

`https://humanetech.community/general/small-is-huge/`

A better scheme for blog posts will create URL's based on month and year of the publish date, like this:

`https://humanetech.community/2019/04/small-is-huge/`

Need to find out if that is supported automatically, or needs to be manually specified specifically and on every blog post.

**Comment by henryrowswell** [comment]
Fortunately Jekyll makes this really easy, by specifying a permalink for all posts in `_config.yml`. The permalink can use any combination of [these](https://jekyllrb.com/docs/permalinks/#placeholders) variables. I created a PR to make it /:year/:month/:slug (slug is the same as title which comes from the filename of the post, but any non-alphanumeric characters are replaced with a hyphen)
