### ISSUE TITLE
Do we really need left menu for categories?

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#35]
We could make categories directly pointing to their description page, i.e. on wellbeing page:

Wellbeing involves the following aspects:

- [Health](https://humanetech.community/wellbeing/health/): physical & mental health

- etc.

The left menu can be avoided and this could improve the mobile experience.

**Comment by aschrijver** [comment]
I like the left-side menu:

- It gives more body / balance to the page visually
- It allows navigation through the entire docs hierarchy, not just the one you are in (e.g. Wellbeing)
- Different sidebar hierarchies are used elsewhere, so it provides consistency
- The side-bar is an important navigational tool, we should not discard it
- Without the side-bar the top of each pyramid top-level page would require to show the sub-pages in the body, taking page space and a page intro that starts lower on the page
- On my Samsung mobile there is no bad experience. Not at all. I see a 'Toggle menu' that allows me to drop down the hierarchy and immediately move to somewhere else without scrolling up or going back to landing page.

**Comment by micheleminno** [comment]
OK, let's keep it.

**Comment by micheleminno** [comment]
Even with the left menu there, do we want to add links to categories in the pyramid page as shown in the top issue description?

**Comment by aschrijver** [comment]
You mean in e.g. the 'Wellbeing' focus page? I think that is nice, as there are short descriptions added as well.

**Comment by micheleminno** [comment]
Yes I mean, should Health etc. in each pyramid focus page be hyperlinks pointing to the specific category description page? I.e.:

Wellbeing involves the following aspects:

- [Health](https://humanetech.community/wellbeing/health/): physical & mental health

- etc.

**Comment by aschrijver** [comment]
Yes, that could be nice to have, the additional links makes it clear we are introducing the doc structure and eases navigation further.
