### ISSUE TITLE
Add a list of most relevant articles, research papers, etc.

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#38]

**Comment by micheleminno** [comment]
I replicated here the pyramid structure, to place any resource in the right pyramid/category.

**Comment by patmatsu** [comment]
Not sure if this is the right place to provide content on books, but here goes:

**Nonfiction**

- Ciarán Mc Mahon (academic psychologist) https://community.humanetech.com/t/new-book-the-psychology-of-social-media/3759 / https://www.routledge.com/The-Psychology-of-Social-Media-1st-Edition/Mc-Mahon/p/book/9781138047754

- James Williams _Stand Out of Our Light: Freedom and Resistance in the Attention Economy_ https://www.cambridge.org/core/books/stand-out-of-our-light/3F8D7BA2C0FE3A7126A4D9B73A89415D

- Bruce Schneier (security expert) _Data and Goliath: The Hidden Battles to Collect Your Data and Control Your World_ https://www.schneier.com/books/data_and_goliath/

- Nicholas Carr _The Shallows: What the Internet Is Doing to Our Brains_ http://www.nicholascarr.com/?page_id=16

- Sherry Turkle _Alone Together: Why We Expect More from Technology and Less from Each Other_ https://www.mit.edu/~sturkle/ 

- Franklin Foer _World Without Mind: The Existential Threat of Big Tech_ https://www.penguinrandomhouse.com/books/533937/world-without-mind-by-franklin-foer/9781101981122

- Will Storr _Selfie: How the West Became Self-Obsessed_ https://www.panmacmillan.com/authors/will-storr/selfie/9781447283669

- Shoshana Zuboff _The Age of Surveillance Capitalism: The Fight for a Human Future at the New Frontier of Power_ https://shoshanazuboff.com/

**Fiction**

- _1984_ https://en.wikipedia.org/wiki/Nineteen_Eighty-Four

- _Fahrenheit 451_ https://en.wikipedia.org/wiki/Fahrenheit_451

**Comment by patmatsu** [comment]
Articles:

**Harm to children**

- https://www.theguardian.com/society/2019/apr/27/technology-threatens-child-development-psychology-expert-warns

**Facial recognition and surveillance** 

- https://www.engadget.com/2018/01/18/china-facial-recognition-uyghurs-xinjiang/

**Community building**

- David Jay https://medium.com/s/story/relationship-machines-675305924d5?sk=b277bbdf2843f22d3a81d79bc20e98ca

**Comment by aschrijver** [comment]
Nice list, Pat. Thanks for collecting.

I think we should move this link collection to the forum, in topics that are clearly indicating that we do this for the Community Hub. Then in this issue tracker we don't get issues that are open indefinitely, but only ones that are quick actions and can be part of the project board's `Todo --> In progress --> Done` workflow.

Or maybe better:

In any post on the forum that contains an interesting link, we:

- Add it to the Community Hub in appropriate location.
- We then edit the post, adding:

---

**Community Team**: Thank you. Your link was added to the Community Hub at [this location](#).

---

In this way on the forum we get reminders of what has been processed, and also the user who posted gets notified of the edit, and will feel honored that they added a valuable contribution.

**Comment by aschrijver** [comment]
Like #69 I added this issue to [Resources project](https://github.com/humanetech-community/community-hub/projects/4).

**Comment by patmatsu** [comment]
When you say the community hub (see your comment above), do you mean this page? https://community.humanetech.com/t/help-build-our-community-hub-and-publish-your-own-blog-entries-now/3824/6

**Comment by patmatsu** [comment]
**Documents**

- [2018-07-networked-authoritarianism-hope-talk.pdf](https://github.com/humanetech-community/community-hub/files/3125839/2018-07-networked-authoritarianism-hope-talk.pdf)

- [826826_Oswald_GenerationTagged_original.pdf](https://github.com/humanetech-community/community-hub/files/3125840/826826_Oswald_GenerationTagged_original.pdf)

- Mozilla Foundation "Internet Health Report 2019" https://internethealthreport.org/2019/

**Comment by patmatsu** [comment]
Sorry to stumble over something small, but I don't understand this part:

"Add it to the Community Hub in appropriate location."

Is this appropriate place a central location or relative, arbitrary one?

**Comment by micheleminno** [comment]
It's the right location (inside the [resources page](https://humanetech.community/resources/)) in the category structure of the pyramids, i.e. wellbeing. 

Check the resource I just added in the resources web page.

**Comment by micheleminno** [comment]
Closing this issue. Good practice:

In any post on the forum that contains an interesting link, we:

- Add it to the Community Hub in appropriate location (pyramid, category).
- We then edit the post, adding:

---

**Community Team**: Thank you. Your link was added to the Community Hub at [this location](#).

---
