### ISSUE TITLE
Background color of instagram button not present

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#39]
In index.html:

![Screenshot 2019-04-22 at 18 38 20](https://user-images.githubusercontent.com/832220/56511821-d1d76a00-652d-11e9-8454-0c2925a2186a.png)

**Comment by aschrijver** [comment]
Yes, this is unfortunate. I had added Instagram before as well, but removed due to this reason. I am not sure, but at the time I thought it was the font-awesome that gave the problem. Maybe not, because it looks like the color boxes are added via CSS.

**Comment by aschrijver** [comment]
It was indeed a setting in the SaSS files. Fixed now.

**Comment by micheleminno** [comment]
I changed the default color to a more 'instagram' like:

![Screenshot 2019-04-23 at 08 02 36](https://user-images.githubusercontent.com/832220/56558195-2ca8aa00-659e-11e9-9d64-18558c034b79.png)

**Comment by aschrijver** [comment]
Nice!
