### ISSUE TITLE
'Our stories' in the main menu

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#40]
I'd like to put 'Our stories' instead of 'Docs' (not pointing to anything right now and kind of redundant with 'Resources' already there).

**Comment by aschrijver** [comment]
Let's wait with that until after the MVP phase and until we know more about the content strategy behind the entire website.

'Docs' is not very imaginative, but what it means to do is document the emerging field of Humane Technology as we discover it. It is the most important body of work of the community.

'Our stories' has completely different meaning than the above. I think if we'll add it at top level, it should be a separate entry. 'Stories' are personal accounts of people, and do not denote 'recorded knowledge'. The Docs section is where official knowledge about HT is recorded.

**Comment by micheleminno** [comment]
Ok, could you put something in Docs for now? Just to avoid the 'page not found' msg..

**Comment by aschrijver** [comment]
Yes, the Docs page should be a top-level container page that has the navigation that you have been filling in: wellbeing, freedom, society, etc.
