### ISSUE TITLE
Home page - menu wording improvements

### ISSUE THREAD

**Issue by polterguess** [humanetech-community/community-hub#58]
1. Activities should become "Our Activities" or "Solutions"
1. Resources - should have the link to GitHub of "List of Existing Resources". It's an activity but it is really now a RESOURCE since it's built already. It should be at the top of the "Resource" page.

**Comment by aschrijver** [comment]
1) is a good change. Will consider using 'Our activities'. 'Solutions' is less appropriate as the 'Docs' section wil contain aggregated knowledge from the forum, and 'Activities' itself includes Meetup groups, which are not solutions.

Could you explain 2) a bit more. Not sure what you mean by this?

**Comment by aschrijver** [comment]
I tested with "Our Activities" which didn't look good, and then "Our activities" which I am doubting about. A single-word entry might be best. But here is how that looks:

![humanetech-mainmenu-our-activities](https://user-images.githubusercontent.com/5111931/56726634-6d93f080-674f-11e9-895d-2ed8bff83a63.png)

**Comment by aschrijver** [comment]
We will leave it as 'Activities' for now. There is another entry 'People' coming and we need to preserve space. Having longer names takes up too much space.
