### ISSUE TITLE
Upcoming events to put on the website

### ISSUE THREAD

**Issue by patmatsu** [humanetech-community/community-hub#68]
I would like to invite people to the "graduation" of participants in round 7 of the Mozilla Open Leaders program.

When | Changed: Tue Apr 30, 2019 11:55am – 1pm Eastern Time - Toronto
Where | https://zoom.us/j/5937811987 (map)
Notes & connection info: https://mzl.la/ol7-demos-b
Blog post on all demos: https://medium.com/p/9f6e0c24db1d
Livestream: https://www.youtube.com/watch?v=Amaw17K-u0Y

**Comment by aschrijver** [comment]
I added this to the Events section. Here is how it looks online:

![humanetech-upcoming-event-moz-ol7](https://user-images.githubusercontent.com/5111931/56846410-58de6680-68cf-11e9-98d8-91322cc64edb.png)

**Comment by patmatsu** [comment]
Looks great; thank you!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
