### ISSUE TITLE
Films, videos, and podcasts need to be included in Resources

### ISSUE THREAD

**Issue by patmatsu** [humanetech-community/community-hub#69]
A few to start with:

**Films**

- _2081_ (adaptation of the story "Harrison Bergeron" by Kurt Vonnegut) https://en.wikipedia.org/wiki/2081_(film)

- _THX-1138_ https://en.wikipedia.org/wiki/THX_1138

- _Fahrenheit 451_ https://en.wikipedia.org/wiki/Fahrenheit_451_(1966_film)

**Videos**

- _The Third Industrial Revolution_ https://impact.vice.com/en_us/article/bj5zaq/watch-vices-new-documentary-the-third-industrial-revolution-a-radical-new-sharing-economy

**Comment by aschrijver** [comment]
In terms of videos we should have the ones where Tristan and other CHT members speak be first and foremost into view in the Resources section.

I have added this to the [Resources project](https://github.com/humanetech-community/community-hub/projects/4) for inlcusion. See https://github.com/humanetech-community/community-hub/issues/38#issuecomment-487359452 for procedure to add more to Resources (we should determine best way).

**Comment by patmatsu** [comment]
Episodes in the [Borja Moya Show](https://www.youtube.com/channel/UC_2o3uWeoQdoBpBdiHJ3O0Q):

- [The Future of DEMOCRACIES Depends on How We Deal with PRIVACY TODAY](https://archive.org/details/20190403TheFutureOfDEMOCRACIESDependsOnHowWeDealWithPRIVACYTODAYInterviewWithEnriqueDansByBorjaMoya) // Interview with Enrique Dans

    Video (Archive.org | [YouTube](https://www.youtube.com/watch?v=CmCGp8TSNro) 1) – [Podcast](https://borjas.blog/episodes/privateid-s01e15-podcast-borja-moya.mp3)

- [COMPUTATIONAL PROPAGANDA: Why Data Extraction Allows MANIPULATION](https://archive.org/details/COMPUTATIONALPROPAGANDAWhyDataExtractionAllowsMANIPULATIONInterviewWithMartaPeir) // Interview with Marta Peirano

    Video (Archive.org | [YouTube](https://www.youtube.com/watch?v=0PId2LL5M0c) 1) – [Podcast](https://borjas.blog/episodes/privateid-s01e16-podcast-borja-moya.mp3)
