### ISSUE TITLE
Add a world map showing HTC Meetup Chapters

### ISSUE THREAD

**Issue by aschrijver** [humanetech-community/community-hub#76]
Our member `@PaulaFairphone` [suggested](https://community.humanetech.com/t/map-design-wanted-mapping-local-meetups/1132/2?u=aschrijver) forking the [Fairphone Community Map](https://map.fairphone.community/) ([github](https://github.com/WeAreFairphone/fprsmap)) to show where meetup groups exist.

The map is already prepared to work with Jekyll and it should be fairly easy to incorporate it on our Meetup Chapters page as an embedded `<iframe>` about the HTC chapters table: https://humanetech.community/activities/meetup-chapters/

**Comment by vbernardes** [comment]
Hi, I've been passionate about the idea behind the Humane Technology movement ever since I first heard about it and would love to contribute in some form. I would like to help out with this issue!

Since I'm new to the community, I'm not sure about the protocol here. Do I need to wait for some go ahead or should I just get to work? :)

**Comment by micheleminno** [comment]
Hi, welcome to HTC! This issue is a good candidate if you want to pick up something that doesn't require a lot of contextual informations. Please go ahead :)

**Comment by vbernardes** [comment]
Thank you! This seems straightforward enough to start with. I'll post here if I have any further questions.

**Comment by micheleminno** [comment]
Assign it to you if you are working on this.

**Comment by vbernardes** [comment]
I don't think I can... maybe I need to be set as a collaborator first?

**Comment by micheleminno** [comment]
Yes you are right, but I can't do it. It doesn't matter.

**Comment by micheleminno** [comment]
@vbernardes I added you as collaborator
check [here](https://github.com/humanetech-community/community-hub/invitations).

**Comment by vbernardes** [comment]
I have a first working version ready, please [check it out](https://vbernardes.github.io/community-hub/activities/meetup-chapters/) and let me know how it looks. Thanks in advance for any feedback!

**Comment by micheleminno** [comment]
This is great @vbernardes, thank you!

**Comment by micheleminno** [comment]
What do you think of showing also 'Other Humane Technology-related Meetup Groups', maybe using another kind of placeholders (and item in the legend)?

![Screenshot 2019-05-30 at 16 54 38](https://user-images.githubusercontent.com/832220/58641541-b06f5800-82fb-11e9-98ca-5ff847387889.png)

**Comment by vbernardes** [comment]
Yes, of course, that's a great next step! I just wanted to get a  basic version up and running first and then get to work to improve it.

Actually, you have already thought about the same improvements I was considering :) They include this topic and #84. I'll go comment on that issue as well.

**Comment by aschrijver** [comment]
Great work @vbernardes and @micheleminno !

I too like the idea to also show the related meetup chapters.

**Comment by vbernardes** [comment]
I have just uploaded an updated version of the map with new placeholders and the “Other Meetup Groups” layer. Please [check it out](http://vbernardes.github.io/htc-map/)!

**Comment by micheleminno** [comment]
Good @vbernardes! I think we can close this issue.
