### ISSUE TITLE
Add blog posts by Biswa Aryal

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#79]
### Text
Imagine your family has more than 4 members . Your child doesn’t go to school because you cannot pay fees. You have to work as a laborer for 10 to 12 hours a day and you earn 5 dollars. You are the only working member of your family.

Due to circumstances like these, people from every part of my country are going to the Middle East in masses just to earn 250 dollars to 350 dollars a month.

Now along comes technology.

When a laborer asks his family what to buy for them, the only answer is a smartphone with a very good camera. And so he sends one or more cellphones costing two months’ salary before sending one dollar for food. And yes, the family is happy with the phones and without food.

Another common story goes like this.

The local porn sites are full of videos that are made in the homes of families like these. They don’t even know how to change the password of their social media account. Some of the nude photos are shared in social media messages by married couples and then leaked by someone from the community who knows their password. Or their private videos are taken from the mobile phone repair shop, which can use simple software to recover all the information stored there.

And the story continues.

It is a community where, per their culture, a lady must not show her full face or body parts except hands and legs to the male members of the family or community. When her nude videos or photos are seen by everybody, there is no chance for her to go to the police station because she cannot utter a word on that topic to anybody in this world. She thinks only of suicide or gets depressed, feeling she will be hated for all of her life.

There are many more stories. People take revenge through social media and cannot contact the police due to the moral damage.

Economically backward countries are facing great damage due to smartphones and social media. This is why I am working with my team to empower youths, to help them save their lives through awareness and motivate them to use cellphones and the internet in beneficial ways.

![14612c69063800e375c58504d90940760a19efe6_2_666x500](https://user-images.githubusercontent.com/832220/57967204-13580b00-795c-11e9-8952-bdb819e23cb0.jpeg)

This picture is captured by my team member : Mr.Durga Prasad Khanal

### Author

- name: Biswa Aryal
- website of my organization: www.livingaroundtechnology.org
- my linkedin profile: https://www.linkedin.com/in/biswa-aryal-181707178/
- "Awareness is best way of realization. We need to be aware about our relationships with technology".

![60163457_2637154119646066_5165644157166813184_n](https://user-images.githubusercontent.com/832220/57680865-d5db4100-762e-11e9-9ba1-2784204edd29.jpg)

**Comment by aschrijver** [comment]
The `_data/authors.yml` file contains some guidelines for new entries:

```yml
# Authors to be referenced in Posts and Pages.
#
# See also: Supported default options at '_includes/author-profile.html'
# More info: https://mmistakes.github.io/minimal-mistakes/layout-author-override/
#
# Avatars must in size 290x310 or similar aspect ratio, to ensure proper circular 
# cutout, and alignmen in grids.
```

**Comment by micheleminno** [comment]
https://humanetech.community/2019/05/damaging-families-in-developing-countries

**Comment by micheleminno** [comment]
How to add credits to an image?
