### ISSUE TITLE
Recent posts in home page doesn't work properly

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#81]
![Screenshot 2019-05-19 at 11 27 29](https://user-images.githubusercontent.com/832220/57983187-3c0cfd00-7a4f-11e9-8381-7962ac9fbd7c.png)

It doesn't show the latest post and doesn't change if clicked.

**Comment by aschrijver** [comment]
Looking quickly at the documentation of the paginator, I think using the paginator is not appropriate. It  _creates_ pages and is not to be used for an embedded section like this. Probably should be changed to show just the 5 most recent `site.posts` and not use the paginator.

**Comment by aschrijver** [comment]
Nice change to have it display as grid. Only issue I see is that currently it only shows the last 2 blog posts for some reason.

**Comment by micheleminno** [comment]
I chose 2, 5 didn't show well in the page.

**Comment by aschrijver** [comment]
Seems like it could hold 4 entries to fill out the entire width?

**Comment by micheleminno** [comment]
in a 5 grid, 2 went on a row and 3 on another row..
but I will try.

**Comment by micheleminno** [comment]
They go in two rows, I don't know why:

![Screenshot 2019-05-27 at 11 35 54](https://user-images.githubusercontent.com/832220/58410994-9de2ed80-8073-11e9-92eb-b3e9c9724bbc.png)


Trying with 3 limit..

**Comment by micheleminno** [comment]
No, the same, restoring to 2.

**Comment by aschrijver** [comment]
Probably this is some CSS setting. Below a blog post 4 entries are shown in a row.

**Comment by bernardini687** [comment]
Hello! I'm sorry for not claiming this issue first, but I forked the project and tweaked the CSS on a new branch, managing to get the 4 recent posts on a row! I'll make a pull request so you can have a look at the changes.

**Comment by micheleminno** [comment]
Thank you @bernardini687, it works perfectly!

**Comment by aschrijver** [comment]
This looks great on the main page, but the issue this has created is that the posts - when shown on their intended location below a blog post - now lack a gutter space between the second and third entry.

PS. The pull request for this issue was #87

**Comment by bernardini687** [comment]
Right! I'm having a look on it. Sorry!

**Comment by bernardini687** [comment]
I opened a Pull Request with the fix from my fork of the project.

**Comment by aschrijver** [comment]
Thank you! Fixed in #88

**Comment by bernardini687** [comment]
You're welcome :)
