### ISSUE TITLE
Change HTC logo and icons

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#89]
After talking with David Jay of CHT, we agree we can change HTC logo (now it's still the CHT one - see [here](https://community.humanetech.com/), top-left corner). 

We need the following files:

- logo - The logo image at the top left of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the site title text will be shown.

- logo small - The small logo image at the top left of your site, seen when scrolling down. Use a square 120 × 120 image. If left blank, a home glyph will be shown.

- digest logo - The alternate logo image used at the top of your site's email summary. Use a wide rectangle image. Don't use an SVG image. If left blank, the image from the `logo` setting will be used.

- mobile logo - The logo used on mobile version of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the image from the `logo` setting will be used.

- large icon - Image used as the base for other metadata icons. Should ideally be larger than 512 x 512. If left blank, logo_small will be used.

- manifest icon - Image used as logo/splash image on Android. Will be automatically resized to 512 × 512. If left blank, large_icon will be used.

- favicon - A favicon for your site, see https://en.wikipedia.org/wiki/Favicon. To work correctly over a CDN it must be a png. Will be resized to 32x32. If left blank, large_icon will be used.

- apple touch icon - Icon used for Apple touch devices. Will be automatically resized to 180x180. If left blank, large_icon will be used.

- opengraph image - Default opengraph image, used when the page has no other suitable image. If left blank, large_icon will be used.

- twitter summary large image - Twitter card 'summary large image' (should be at least 280 in width, and at least 150 in height). If left blank, regular card metadata is generated using the opengraph_image.

**Comment by micheleminno** [comment]
[Here](https://github.com/humanetech-community/community-hub/tree/master/assets/images)'s what we have right now, currently used for [our website](https://humanetech.community).

**Comment by aschrijver** [comment]
The logo's we currently have are all in the Styleguide repo: https://github.com/humanetech-community/styleguide/tree/master/logos

**Comment by micheleminno** [comment]
Icons updated.
