### ISSUE TITLE
Add new London and Berlin meetups

### ISSUE THREAD

**Issue by micheleminno** [humanetech-community/community-hub#90]
Update the meetups page (both text and map) with new events.

**Comment by micheleminno** [comment]
- https://community.humanetech.com/t/london-consciously-digital-meetup/4149
- https://community.humanetech.com/t/humane-tech-meetup-berlin-1/4143/2

**Comment by aschrijver** [comment]
The Berlin meetup has been renamed. It is now in the Other meetups table and used to be called Ethical Tech.

PS. I think it is better to have issues that can be closed once the work is done, rather than have them be 'continuous'.

**Comment by micheleminno** [comment]
Add user @quanders to Berlin meetup.

**Comment by vbernardes** [comment]
Hi @micheleminno, thanks for the heads up. Please review #92.

**Comment by patmatsu** [comment]
Please add this Berlin meetup info from Welf von Hören (@welf at the forum):

#humanetech meetup at CODE University of Applied Sciences Berlin, at the Factory Berlin Campus next to Görlitzer Park!

Sign up here: https://www.meetup.com/de-DE/Humane-Technology/events/262012137/

**Comment by vbernardes** [comment]
Hi @patmatsu, that link refers to an event that was held on June 17th. From the [forum discussion](https://community.humanetech.com/t/humane-tech-meetup-berlin-1/4143/2), it seems they intend to make it a monthly event.
Maybe we should wait for the next event so we can put up the new Meetup link?

**Comment by patmatsu** [comment]
Thanks for the question.

Welf said it has become a regular event due to the success of the first one.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by patmatsu** [comment]
Sorry, I read your message too quickly.

I will write to Welf and ask him.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by patmatsu** [comment]
Here is what Welf said:

"There might also be other locations from time to time but I guess the main location is the one at CODE University, yes!"

Can we make the location the university?

**Comment by vbernardes** [comment]
Hi @patmatsu, I've updated the location of the Berlin meetup on the map to point to CODE University.

I don't think there's anything that needs to be done for the table on the [Meetup Chapters page](https://humanetech.community/activities/meetup-chapters/), right?

**Comment by patmatsu** [comment]
Thank you, Vitor! Yes, you're right about the table.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vbernardes** [comment]
Great, so I think it's okay to close this. Fixed by https://github.com/vbernardes/htc-map/commit/81d235634c64feb9585d83cbf159244f965c3470.

**Comment by patmatsu** [comment]
I believe so, but perhaps the final word should come from Michele?

Thank you for the awesome work, Vitor.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
